import type { NextPage } from "next";
import Head from "next/head";
import UtilItemCard from "../components/utilCard";

const Home: NextPage = () => {
    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
                <h1 className="text-5xl font-extrabold leading-normal text-gray-700 md:text-[5rem]">
                    Useful <span className="text-purple-300">Utilities</span>{" "}
                    App
                </h1>
                <p className="text-2xl text-gray-700">The tools included:</p>
                <div className="mt-3 grid gap-3 pt-3 text-center md:grid-cols-2 lg:w-2/3">
                    <UtilItemCard
                        name="Base64 Conversion"
                        description="Simple clientside base64 convertion tool"
                        href="/base64"
                    />
                </div>
            </main>
        </>
    );
};

export default Home;
